//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string SponsorId { get; set; }
        public Nullable<int> SponsorFloor { get; set; }
        public string SponsorAddress { get; set; }
        public string PlacementId { get; set; }
        public Nullable<int> PlacementFloor { get; set; }
        public string PlacementAddress { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> Activity { get; set; }
        public Nullable<bool> Lock { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> Token { get; set; }
        public string SecrectKey { get; set; }
        public string ResetPasswordKey { get; set; }
        public string GoogleAuthenticatorSecretKey { get; set; }
        public Nullable<bool> IsGoogleAuthenticator { get; set; }
        public string Country { get; set; }
        public Nullable<int> IsKYC { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<bool> LockWithdraw { get; set; }
        public string Pass2 { get; set; }
        public string TelegramChatId { get; set; }
        public string AuthTelegramBot { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<double> SalesBonusPlusPercent { get; set; }
        public string CoverImage { get; set; }
        public string ShopName { get; set; }
        public Nullable<System.DateTime> DateExp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
    }
}
