//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLicense
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string BusinessCode { get; set; }
        public string Logo { get; set; }
        public string LicenseImage { get; set; }
        public string DistributionAgentContractImage { get; set; }
        public Nullable<int> Status { get; set; }
        public string ShopId { get; set; }
        public Nullable<int> followers { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Banner { get; set; }
        public string NoteStatus { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    }
}
