//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartUser
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<System.Guid> PropertyId { get; set; }
        public string Currency { get; set; }
        public string ShopId { get; set; }
    }
}
