//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CViewLog
    {
        public int id { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string IdAddress { get; set; }
        public string ShopId { get; set; }
    }
}
