//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserId { get; set; }
        public string Code { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> FeeShip { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> SubTotalUSD { get; set; }
        public Nullable<double> DiscountUSD { get; set; }
        public Nullable<double> TotalUSD { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string Currency { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public Nullable<int> PaidStatus { get; set; }
        public string ShopId { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Street { get; set; }
        public string FullAddress { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Receiver { get; set; }
        public Nullable<double> TotalWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
