//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> DiscountUSD { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> SubTotalUSD { get; set; }
        public Nullable<double> TotalUSD { get; set; }
        public string Currency { get; set; }
        public Nullable<System.Guid> PoolId { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
