//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListCoin
    {
        public System.Guid Id { get; set; }
        public string EmailUser { get; set; }
        public string UserId { get; set; }
        public string RelationshipProject { get; set; }
        public Nullable<System.DateTime> DateLaunch { get; set; }
        public string DetailProjectDescription { get; set; }
        public string Platform { get; set; }
        public string MediaCoverage { get; set; }
        public string Country { get; set; }
        public string Website1 { get; set; }
        public string Website2 { get; set; }
        public string PlatformOfContract { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string BlockExplorer { get; set; }
        public string Affiliation { get; set; }
        public string Whitepaper { get; set; }
        public string Twitter { get; set; }
        public string Telegram { get; set; }
        public string Reddit { get; set; }
        public string Facebook { get; set; }
        public string ProjectVideo { get; set; }
        public string Linkedln { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string PriceLink { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string ChainName { get; set; }
        public string Contract { get; set; }
        public Nullable<int> Decimals { get; set; }
        public string Symbol { get; set; }
        public string Logo { get; set; }
        public string ProjectName { get; set; }
        public string SymbolLabel { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> DateUpdatePrice { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsWithdraw { get; set; }
        public Nullable<bool> IsDeposit { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
    }
}
