//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoolAcceptCountry
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PoolId { get; set; }
        public Nullable<int> CountryId { get; set; }
    }
}
