//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pool
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsPriceRealTime { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> USDTotal { get; set; }
        public Nullable<double> USDRemaning { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> CollectedCoin { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<double> PercentAcceptUSDPay { get; set; }
        public Nullable<int> TotalProduct { get; set; }
        public Nullable<bool> AcceptAllCountry { get; set; }
        public Nullable<bool> AcceptAllCategory { get; set; }
        public Nullable<bool> AcceptAllShop { get; set; }
        public Nullable<bool> AcceptAllProduct { get; set; }
    }
}
