//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Guarantee { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string Origin { get; set; }
        public string Manufacture { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.Guid> BrandNameId { get; set; }
        public Nullable<bool> Hot { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> CountRating { get; set; }
        public Nullable<double> QuantityAvailable { get; set; }
        public Nullable<double> QuantitySold { get; set; }
        public Nullable<double> QuantityTotal { get; set; }
        public Nullable<int> Expiry { get; set; }
        public Nullable<int> ExpiryType { get; set; }
        public Nullable<int> CountView { get; set; }
        public Nullable<double> KValue { get; set; }
        public Nullable<double> KValuePercent { get; set; }
        public string UserId { get; set; }
        public string Slug { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<double> Weight { get; set; }
        public string SKU { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public string Unit { get; set; }
        public string CateNode { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
