//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLicense
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string ProductImage { get; set; }
        public string LicenseImage { get; set; }
        public string ShopId { get; set; }
    }
}
