//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopLogistic
    {
        public System.Guid Id { get; set; }
        public string LogisticName { get; set; }
        public string Logo { get; set; }
        public Nullable<double> ShipPrice { get; set; }
        public Nullable<double> MaxWeight { get; set; }
        public Nullable<double> StepWeight { get; set; }
        public Nullable<double> StepPrice { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string ShopId { get; set; }
    }
}
