//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopVoucher
    {
        public System.Guid Id { get; set; }
        public string ShopId { get; set; }
        public string NameVoucher { get; set; }
        public string Code { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
