//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string Country { get; set; }
        public string Receiver { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string ZipCode { get; set; }
        public string Street { get; set; }
        public string Phone { get; set; }
        public string Type { get; set; }
        public string FullAddress { get; set; }
    }
}
