//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletAddress
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string ChainName { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Address { get; set; }
        public string Symbol { get; set; }
        public string PrivateKey { get; set; }
        public Nullable<int> Decimals { get; set; }
        public string SmartContract { get; set; }
        public string SymbolLabel { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
